### ISSUE TITLE
Cancel crafting

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#100]
Cancel crafting is a request from @CasparPetch

It is commonly used for a trick in regular any% for transporting bulk items, by crafting 500 green science packs.
[crafting_queue api](https://lua-api.factorio.com/latest/LuaControl.html#LuaControl.crafting_queue)
[cancel_crafting api](https://lua-api.factorio.com/latest/LuaControl.html#LuaControl.cancel_crafting)

I doubt it has much utility for most TAS, but for completeness sake it is worth to consider.

**Comment by MortenTobiasNielsen** [comment]
I have had a need for it a few times in my run, but it has until now been easily solved by using a chest. I would though imagine that it would become very useful in the later stages.
