### ISSUE TITLE
Hotbar

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#118]
It would be nice to have a sort of hotbar in the generator GUI:

A simple short list of task that can be reused
It could auto adds the most recent task, if so then it should be possible to pin tasks.

**Comment by MortenTobiasNielsen** [comment]
I would need to see some kind of mock up of this. Currently I have no idea when I would use it. If I want a recently used step I double click the step. There might be a few things like mining a specific spot in the early game or move to a hotspot location, but then I add it to a template, given that I commonly need to perform a lot of steps on the way, which won't be the same every time. 

When would you use this?

**Comment by theis999** [comment]
I will give a more elaborate example when the idea is more concrete.
