### ISSUE TITLE
Move items to hand

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#119]
It would look nice, if when you want to build something that the TAS moves that item before hand.

**Comment by theis999** [comment]
![image](https://user-images.githubusercontent.com/18309265/207718990-9d750b94-085a-451c-92aa-9e3fee39b3b1.png)
![image](https://user-images.githubusercontent.com/18309265/207719045-79a6efbe-704f-47b8-9b1c-6d14346c51f4.png)

Moves the item into the hand as seen by the images. I can see why my description could be hard to read, i hope this is clearer

**Comment by MortenTobiasNielsen** [comment]
I see - yeah that would be a nice "cherry on top" kind of thing to have.

**Comment by theis999** [comment]
```
local a = player.character.get_main_inventory()
local b = a.find_item_stack(item)
player.cursor_stack.set_stack(b)
```
It looks weird when the cursor isn't near the target

**Comment by MortenTobiasNielsen** [comment]
Ohh yeah, I guess the cursor is just some random place - that might not give the effect we want. :(

**Comment by theis999** [comment]
It might be more simple to blueprint entities you want to place, and mark for deconstruct entities you want to mine. Which might give most of the same effect.
