### ISSUE TITLE
auto save

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [MortenTobiasNielsen/Factorio-TAS-Generator#121]
I often find that I have forgotten to save, sometimes for hours, so It would be nice if the tool could auto save at a set interval. I think I would set it to something like once every minute.

**Comment by theis999** [comment]
Maybe instead of a timer, it creates an auto-save file on script generation (ALT+G).

**Comment by MortenTobiasNielsen** [comment]
Agreed - I think a time check on script generation and if x minutes have passed it creates and auto save (nameOfRun_time), in an auto save folder.

**Comment by MortenTobiasNielsen** [comment]
I would like to have more than 1 save file, given that I might do multiple things and find out that I have done something which doesn't work (normally deleted something or moved something out of order) and I need to go back e.g. 10 minutes to find a save which doesn't have the misalignment.

**Comment by MortenTobiasNielsen** [comment]
Maybe not, but what would you use as an indicator for the files?

Not sure what that means. :)

**Comment by theis999** [comment]
There exists tools for the job, which might be worth checking out.

If we were to create auto save files ourselves, we can use a format like: <tas_name>_temp_<x>

**Comment by theis999** [comment]
However i think activating git on your save file directory is the best. Since it gives more options than just viewing older versions of the files.
Making a tool that auto-commits to git seems slightly more complicated. It does however look like a problem that others have had too: https://stackoverflow.com/questions/420143/making-git-auto-commit/14002536#14002536

**Comment by MortenTobiasNielsen** [comment]
I don't see how you would get multiple files, using <tas_name>temp - won't you just overwrite the same file over and over again?

It seems pretty overkill to have git versioning on saved files and I don't want to force users to install git and make an account to some sort of git repository website, to make the tool work. What is the problem with just saving files? Users can save to one-drive, dropbox or something else, if they want to ensure the save files won't be deleted.

**Comment by theis999** [comment]
#137 solved.

I still think that using git, would give a better solution for long term storage. But auto-committing might not be a good idea. So we will leave it up to users.

Git is useable local, even without making a repository on some git webpage. Giving you access to branching and versioning.
