### ISSUE TITLE
Search case sesitivity

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [MortenTobiasNielsen/Factorio-TAS-Generator#124]
It would be nice if the search functionality was case insensitive, so searching for e.g. start/save would work

**Comment by theis999** [comment]
It is easy enough for 4/5 strings fields since they are just capitalized. It is unclear to me if you search for a comment, whether case matters or not.

Anyway google gives us this code:
```
// c++20
#include <ranges>
#include <algorithm>
#include <string>

bool iequals(const std::string_view& lhs, const std::string_view& rhs) {
    auto to_lower{ std::ranges::views::transform(std::tolower) };
    return std::ranges::equal(lhs | to_lower, rhs | to_lower);
}
```
