### ISSUE TITLE
Pickup (f) doesn't work in compatibility mode

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#155]
When in "old" mode pickup_ticks is never set, so the tas doesn't know it is in pickup state. However it also doesn't progress the step counter forward, so the character just stands there.

**Comment by MortenTobiasNielsen** [comment]
There is not compatibility mode for pick up. Currently the user is supposed to align the run with the new pickup feature, but I might do something to fix it.

**Comment by theis999** [comment]
I can confirm that the state does go into compatibility version of the doStep.
Getting a good solution is likely impossible, given how different the old and the new version is. So spend an appropriate amount of time
