### ISSUE TITLE
Putting 'all' modules into wreck slot eats all items

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#161]
I haven't tested how much this generalizes. However:
If you use [put, all, modules x] into a beacons [wreck] slot then it will consume all of them even though a beacon can only hold 2 modules.

**Comment by MortenTobiasNielsen** [comment]
Interesting - how did you stumble upon this bug?

**Comment by theis999** [comment]
The TAS helper tool by pellet12 auto-generated the step

**Comment by MortenTobiasNielsen** [comment]
I was able to solve #160, but I don't really understand this one. For some reason "get_insertable_count" thinks that it is able to insert 100 into the module inventory.
![image](https://user-images.githubusercontent.com/48355480/217051105-b631b4be-4f91-4f12-b972-af72b5f1b4db.png)

**Comment by theis999** [comment]
The bug has been [reported to factorio](https://forums.factorio.com/viewtopic.php?f=7&t=105155).
I will update here when I get update there.

It seems that problem extends to module inventories of assemblers too, so I expect it to wrong for all module inventories.

**Comment by theis999** [comment]
It seems the factorio team wont fix this issue. 

Which obviously leaves us with some problems. 
For this specific issue we can just use the return value of [insert](https://lua-api.factorio.com/1.1.74/LuaControl.html#LuaControl.insert) to remove items from the character.

**Comment by MortenTobiasNielsen** [comment]
Unfortunate, but fair enough.
