### ISSUE TITLE
Compatibility mod save

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#164]
Compatibility mod save creates save state before advancing the step. Which means that on load it thinks the next step is save step.

Swapping the lines like this, might fix it.
![image](https://user-images.githubusercontent.com/18309265/218224788-caec2c65-2c93-4ad6-a7e5-c04b0d5ef5bb.png)

**Comment by MortenTobiasNielsen** [comment]
It seems reasonable that this would fix the problem. Who is the originator of the issue - so we have a way to test if it fixes the problem they see?

**Comment by theis999** [comment]
[autosave0.zip](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/files/10712923/autosave0.zip)
[AnyPercent_TAS_by_Zaspar (3).txt](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/files/10712924/AnyPercent_TAS_by_Zaspar.3.txt)

Zaspar saw the issue, i ran it through the debugger to understand the problem. 
I can easily upload the fix. Though i do have issues with spending too much time on Compatibility mode and i dont know what follow problems this could cause.

**Comment by MortenTobiasNielsen** [comment]
Agreed. Most likely it is only one person who needs compatibility mode, so if this seems to fix the issue I will just merge it in. :)
