### ISSUE TITLE
Paint commands that adds walk steps

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#165]
I can see that Zaspar has trouble figuring out when a Walk step gets added by the generator.

It would be nice to indicate when a command adds a walk step, so it is visible in the generator without running the game.
That way it would also be easier to pin point problematic tasks.

One way could be to color a part of the grid line, on generate script.

**Comment by MortenTobiasNielsen** [comment]
I agree that this is a problem. I usually solve it by opening the script and see if there are walk steps with impossible coordinates, which clearly isn't a good solution. 

I guess it would be possible to run the distance calculation on each step added and color the text red if it is not within reach, I am though a little in doubt users will understand why it is happening.

**Comment by theis999** [comment]
Yeah I would like deal with it the same way, but we are both programmers with integral knowledge of the system 😎

There are many ways to deal with it to a more general user. 
I like the idea of painting: 
- It would allow us to target the problematic tasks visually
- It doesn't block the user (like a pop-up)
- It is easy to see when scrolling a huge list of steps

But your concern is valid

**Comment by MortenTobiasNielsen** [comment]
Lets go with the painting solution and hope users doesn't get too confused. :)
