### ISSUE TITLE
Ability to delete multiple tasks at once

### ISSUE THREAD

**Issue by CasparPetch** [MortenTobiasNielsen/Factorio-TAS-Generator#187]
Control clicking multiple tasks can select them all at once, but clicking delete will only delete one of them at a time when the tasks that were selected are separated by a gap

**Comment by theis999** [comment]
This is intended behavior, and as such not bug.
Though we should still change it.

**Comment by MortenTobiasNielsen** [comment]
Agreed. It is implemented due to a limitation which no longer exists. So it would be nice if it was changed.
