### ISSUE TITLE
Retain cmb_item value

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#192]
> Nice work - it has been annoying that it changes the item when just changing the step type. It would be nice it was checked if the new list also has the item. So it keeps assembling machine if I have just taken an assembling machine, I change it to build and then change it to recipe.

When changing command type the suggested list for cmb_item changes, which changes it's value.
We have two options, we can retain a last_value per list or try to see if the old value in cmb_item is contained in the new list.

**Comment by MortenTobiasNielsen** [comment]
It would be nice if item was kept as assembling machine 1 if I have the following sequence of steps:

- Take: Assembling machine 1
- Build: Assembling machine 1
- Recipe: Assembling machine 1

All of the item lists will have assembling machine 1 (craft as well), so it would be nice that it kept the chosen item unless it isn't in the new list. So I guess that would be option two. It would though also be nice if the last value was saved for a specific step type if the old value is not in the new list, given that it is much more likely that the user needs the last value than the arbitrary first value of the list.

**Comment by theis999** [comment]
We can do both, as they are not mutually exclusive.
