### ISSUE TITLE
Save the current row, so it can be scrolled to when the tool is opened. 

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [MortenTobiasNielsen/Factorio-TAS-Generator#202]
It would be the cherry on top if the tool would scroll to where the user left of. It is really nice that it opens the last save, but then I need to remember where I was and where that is in the 1000's of steps.

**Comment by theis999** [comment]
The two things are unrelated, as the current would be tas run file specific where the last tas is specific to the tool.

We would need to save selectedRowBlocks to be accurate, which is doable.
Then reselect the rows.
Then scroll to the top row of the first block.

While we are at it, we might as well double click the top row.

**Comment by MortenTobiasNielsen** [comment]
Agreed. I would be fine for me, if it is just the top row of what ever is selected which is saved. I very rarely (if ever) save with multiple rows selected. 

Yeah that would also be nice.
