### ISSUE TITLE
Reload script file button

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#208]
The tas helper mod by Pallet12 is very convenient, but the export is clunky. We could help this by having a button that reloads the current script file.

**Comment by MortenTobiasNielsen** [comment]
That would be nice. Could maybe have a F5 shortcut. :)

**Comment by theis999** [comment]
Good idea!

**Comment by theis999** [comment]
Unless it would be better to have an input box where the user can write strings directly to end of the step grid.

**Comment by MortenTobiasNielsen** [comment]
That would be pretty awesome, if there was an import steps button. So the user could just take the steps generated by the recorder tool and put it directly into the tool. Great idea. :)

**Comment by theis999** [comment]
A simple mock-up:
![image](https://user-images.githubusercontent.com/18309265/225036004-45585fc5-8f1e-4711-bd5d-37a055c16912.png)

Does this match what you intended?

**Comment by MortenTobiasNielsen** [comment]
Yeah something like that would be nice.

Might be nice if it is possible to add the steps to a template, which already exists.
