### ISSUE TITLE
Special commands

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#209]
There are a few special commands that we could consider if we want to support:

Inserter filter mode - whitelist / blacklist
Set character color (wx uses colour, and factorio uses color)
Clean pipe system

Equip armor
Insert equipment (position)
Equip weapon (slot)
Equip ammo (slot)

**Comment by MortenTobiasNielsen** [comment]
I guess some players really want the character to be a specific color, so they would like the color changing and I guess it would be relatively easy to implement now the color wheel is there. 

Most of the others I think should be unnecessary in a TAS.  Filter inserts are are relatively expensive both the research and craft, and it should be possible to solve whatever problem with careful planning. The same can be said for cliff explosives. 
Cleaning a pipe system sounds like a terrible waste of resources, when the literally have months to plan out their run.

**Comment by theis999** [comment]
I just wanted a written collection of commands, so they don't occupy my mind. Which is also why i set the label to on-hold. I don't anticipate implementing any of them **without a request** for it.

I agree with you that none of these are likely to be used. Filter blacklist <-> whitelist being the exception. Filter inserters are in the same technology as fast inserters, so for any% you will have access to them. Filter inserters are also cheaper than splitters, so they are likely to be used. However the uses of a blacklist filter is questionable.

This is likely the API method for [throwing items](https://lua-api.factorio.com/1.1.78/LuaPlayer.html#LuaPlayer.use_from_cursor)
[Clear pipes](https://lua-api.factorio.com/1.1.78/LuaEntity.html#LuaEntity.clear_fluid_inside)
