### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#21]
It would be nice if (task) groups are added to the task list, as a single task. 

This would allow the user to compress the task list in the TAS editor. Hiding stuff that is no longer being worked on, or stuff beyond a save point.

This is likely a considerable rewrite, so it might not be worth it.

**Comment by MortenTobiasNielsen** [comment]
I think it would be a lot of work, and I often find myself changing a few things after adding a group. I might take a look at it anyway at some point. :)

**Comment by theis999** [comment]
_I was thinking was about this:_
I do think that Group and Template are too similar. Groups are effectively just templates without offsets.
I do see the value of having a hotbar (of sorts), which seem like how you use groups.
I think we have a problem with the task list getting unwieldy when one have +100 tasks. 

Having groups as task would condense the task list, and could allow the user to modify a bunch of tasks at the same time (which seems both neat and scary).

However, an alternative approach would be to add navigational properties to the task list (segments). So the task list, becomes a list of collapsible segments, where each segment holds a part of the whole task list.
