### ISSUE TITLE
Print comments

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#22]
The new comment field is nice, and it is very neat to have the option of putting comments on any task.

However, unintuitively the comments aren't printed in game.

Printing comments during the run, could also help the viewer notice _cool_ stuff that the TAS developer is particularly proud of.

**Comment by MortenTobiasNielsen** [comment]
I think it would be nice, but it is also non-trivial to do (in terms of time).
