### ISSUE TITLE
Step type sub panels

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#224]
It would be neat if the different action types were organized slightly more.
For instance this could be done by adding three sub panels:

- Character interactions
- Building interactions
- Game interactions

Before
![image](https://user-images.githubusercontent.com/18309265/227470400-ee6f3c1a-e0b9-47d0-a097-dce6f492c841.png)

After-mockup
![image](https://user-images.githubusercontent.com/18309265/227475926-9a4b28db-cb9b-42c0-b98a-a3d72a3d17c0.png)

Hopefully this would make it slightly faster to scan the action types for the correct one

**Comment by MortenTobiasNielsen** [comment]
I usually don't use the steps panel, given that it almost always is faster to click steps already configured. It would though still provide a better user experience, especially in the beginning of a TAS where configured steps aren't available.

**Comment by theis999** [comment]
It matters more for the less frequently used types.
There are also more types in the pipe-line (shooting etc.), so more organization could become more important in the future.

There are however many ways to organize them. We can go ahead with this idea or another suggestion?

**Comment by MortenTobiasNielsen** [comment]
Agreed - it might not be possible to do it nicely with the elements available in WxFormBuilder.

**Comment by theis999** [comment]
I couldn't get a clean looking header for the panels.
