### ISSUE TITLE
Doubleclick on imported step with amount 1.000000

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#242]
This could be a problem in either the GUI or the step planner. Either way double clicking a task with amount `1.000000` doesn't get converted correctly to `1`. Breaking the functionality of spinner arrows.

**Comment by MortenTobiasNielsen** [comment]
I guess this a something to do with the GUI expecting an integer, so it doesn't know what to do with the double.

**Comment by theis999** [comment]
That sounds plausible.

**Comment by theis999** [comment]
Seems to be resolved
