### ISSUE TITLE
Warning on empty crafting queue

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#244]
The warning system makes it fairly simple to see where tasks can be optimized. It would in this regard be helpful to raise a warning in case the player empties the crafting queue.

**Comment by MortenTobiasNielsen** [comment]
Agreed. That would be really nice. We do though need to have some kind of grace period, given that it is expected that the crafting queue is empty multiple times the first X minutes of a game

**Comment by theis999** [comment]
You probably correct, which makes it slightly tricky.

**Comment by MortenTobiasNielsen** [comment]
I guess it could be one of the modifiers. So the user would specify an amount of ticks (or seconds) before this takes effect.
