### ISSUE TITLE
Refactor and use utils.h objects

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [MortenTobiasNielsen/Factorio-TAS-Generator#48]
There are a lot of objects not being used (which maybe should be used) and some sort of code duplication in utils.h. We should refactor and use these objects more consistently throughout the codebase. 

It might make sense to split utils.h into two. One with all the lists for information and one with the structs.

**Comment by theis999** [comment]
I wouldn't mind having util functions, util data (data lists, enums) and util structures (structs, typedefs).

I saw somewhere else that it was recommended, to further split every util function implementation into it's own file.

**Comment by MortenTobiasNielsen** [comment]
I would normally split everything into its own file, it just doesn't seems like a common thing to do in c++ and it doesn't seems to have a good way to structure the many files which would be created.
