### ISSUE TITLE
Factorio launch configuration

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#85]
We need the capacity to run factorio, with some specific configurations, for a number of smart potential features.

Configurations should include: 
- a launch file 
- map generation string

Potential features could include:
- Generations of list of entities, item & recipes for modded gameplay
- Run verification / unit testing
- Segment benchmarking, listing how much time a segment takes and maybe how much stuff you have in inventory (for cooperative TAS development)
- Machine learning
- Generation of an initial entity list: ships parts, rocks & trees. 
- Generation of a tile list
- TAS porting: mod list and map string

**Comment by MortenTobiasNielsen** [comment]
@theis999 that sounds awesome. It is nice to have someone contributing, which have a much better understanding of how to integrate with factorio. 

- Would that be configuration of the TAS tool to be able to make a TAS for a modded game? 
- I what way would it be verified/unit tested? 
- I think it would be really difficult to make a meaningful beanchmark. Is it for instance best to have used time setting all the recipes of assemblers or to have run over to pick up stuff? 
- Is it possible to write production, electricity and technology stats somewhere, so it can be used to inform an algorithm? It might also be useful for benchmarking. 
- Is it possible to generate this list in game, with a marking of where the player would spawn and how many of each entity is within a certain distance? That would greatly improve the search for good maps. 
- Not sure what that is. 😊
- Would also be nice to have.

**Comment by theis999** [comment]
It is hard to tell how exactly a feature would look before it is made. 
- Most modded items should importable, so yes. There are a few that could be hard, like the windmills in Nullius.
- For example we could verifying that entities are within reach.
- We could start with number of ticks elapsed and research completed as a benchmark.
- There is a [mod for production](https://mods.factorio.com/mod/some-benchmark). Reading the electric networks might be hard. Reading which [Technologies has been researched](https://lua-api.factorio.com/latest/LuaTechnology.html#LuaTechnology.researched) should be trivial.
- It is simple enough to [find entities](https://lua-api.factorio.com/latest/LuaSurface.html#LuaSurface.find_entities_filtered) - i doubt that it would help find good maps. Since the amount of variables are simply too high. However someone in team steelaxe did make a script that processed all seeds and found some promissing maps.
- A list of tiles (or map) on a map, for vanilla it mostly matters for water->landfill, but [alien biomes](https://mods.factorio.com/mod/alien-biomes) have many tiles with reduced speed that we might want to avoid.
-

**Comment by MortenTobiasNielsen** [comment]
True. :)
- Makes sense. 
- The walking algorithm should ensure that the player are within reach for a specific interaction. 
- Some might find it useful, I am though a little hesitant given that I wouldn't be able to use that benchmark, it simply wouldn't be able to tell me anything useful. 
-  I guess it would be needed to have continues reading of production, the electric networks, researched technologies + the percentages of not finished research. 
- I think it would help massively to know where the player spawns on the map and at least being able to know that there are at least x amount of huge rocks and wood within a distance of y - it would make it much easier to find a viable map for specific challenges. I wasn't aware that someone had done that, do you know how and are you sure it was all seeds - isn't that like 10 billion maps?
- Fair.
